package com.quochuy.security.config;

import com.nimbusds.jose.jwk.source.ImmutableSecret;
import com.quochuy.security.CustomUserDetails;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.oauth2.jose.jws.MacAlgorithm;
import org.springframework.security.oauth2.jwt.JwtClaimsSet;
import org.springframework.security.oauth2.jwt.JwtDecoder;
import org.springframework.security.oauth2.jwt.JwtEncoder;
import org.springframework.security.oauth2.jwt.JwtEncoderParameters;
import org.springframework.security.oauth2.jwt.JwsHeader;
import org.springframework.security.oauth2.jwt.NimbusJwtDecoder;
import org.springframework.security.oauth2.jwt.NimbusJwtEncoder;
import org.springframework.stereotype.Component;

import javax.crypto.spec.SecretKeySpec;
import java.time.Instant;
import java.util.stream.Collectors;

/**
 * Creates and decodes locally signed JWTs.
 *
 * <p>The app uses HS256 with the shared {@code app.jwt.secret}. Access tokens
 * are sent to browsers as HTTP-only cookies and are also accepted through the
 * {@code Authorization: Bearer ...} header by the resource server.</p>
 */
@Component
public class JwtTokenUtil {
	private final JwtEncoder encoder;
	private final JwtDecoder decoder;

	@Value("${app.jwt.secret}")
	private String jwtSecret;

	@Value("${app.jwt.issuer}")
	private String jwtIssuer;

	public JwtTokenUtil(@Value("${app.jwt.secret}") String jwtSecret) {
		this.jwtSecret = jwtSecret;
		this.encoder = new NimbusJwtEncoder(new ImmutableSecret<>(jwtSecret.getBytes()));

		SecretKeySpec spec = new SecretKeySpec(jwtSecret.getBytes(), "HmacSHA256");
		this.decoder = NimbusJwtDecoder.withSecretKey(spec)
				.macAlgorithm(MacAlgorithm.HS256)
				.build();
	}

	/**
	 * Generic token builder for legacy or special-purpose JWTs.
	 *
	 * <p>Most authenticated browser traffic should use {@link #generateAccessToken}
	 * so the token contains the session id and token-version claims used by the
	 * security filters.</p>
	 */
	public String createToken(
			String subject,
			String userName,
			String email,
			String scope,
			long expirationSeconds
	) {
		Instant now = Instant.now();
		JwtClaimsSet claims = JwtClaimsSet.builder()
				.issuer(jwtIssuer)
				.issuedAt(now)
				.expiresAt(now.plusSeconds(expirationSeconds))
				.subject(subject)
				.claim("roles", scope)
				.claim("userName", userName)
				.claim("email", email)
				.build();

		return this.encoder.encode(
				JwtEncoderParameters.from(JwsHeader.with(MacAlgorithm.HS256).build(), claims)
		).getTokenValue();
	}

	/**
	 * Creates a short-lived access token for an authenticated application user.
	 *
	 * <p>Important claims:</p>
	 * <ul>
	 *   <li>{@code sub}: user id.</li>
	 *   <li>{@code sid}: auth session id, used to connect the JWT to refresh state.</li>
	 *   <li>{@code roles}: Spring Security authorities such as {@code ROLE_USER}.</li>
	 *   <li>{@code ver}: token version, used to revoke old tokens after account changes.</li>
	 * </ul>
	 */
	public String generateAccessToken(Authentication authentication, String sessionId) {
		CustomUserDetails user = (CustomUserDetails) authentication.getPrincipal();
		String scope = authentication.getAuthorities()
				.stream()
				.map(GrantedAuthority::getAuthority)
				.filter(authority -> authority.startsWith("ROLE_"))
				.collect(Collectors.joining(" "));

		Instant now = Instant.now();
		JwtClaimsSet claims = JwtClaimsSet.builder()
				.issuer(jwtIssuer)
				.issuedAt(now)
				.expiresAt(now.plusSeconds(3600))
				.subject(user.getUserId().toString())
				.claim("sid", sessionId)
				.claim("roles", scope)
				.claim("userName", user.getUsername())
				.claim("email", user.getEmail() != null ? user.getEmail() : "")
				.claim("ver", user.getTokenVersion())
				.build();

		return this.encoder.encode(
				JwtEncoderParameters.from(JwsHeader.with(MacAlgorithm.HS256).build(), claims)
		).getTokenValue();
	}

	/**
	 * Creates a signed refresh JWT for legacy flows.
	 *
	 * <p>The current browser session flow uses opaque refresh tokens generated by
	 * {@code TokenFactory} and stored as hashes in {@code auth_sessions}. Do not
	 * mix this JWT refresh token with that session rotation flow.</p>
	 */
	public String generateRefreshToken(Authentication authentication) {
		CustomUserDetails user = (CustomUserDetails) authentication.getPrincipal();
		return createToken(
				user.getUserId().toString(),
				user.getUsername(),
				user.getEmail(),
				"",
				604800
		);
	}
}
